services:
  mysql:
    image: mysql:8.4.3
    container_name: tz-open-next-mysql
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_DATABASE: tz-open
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: HM62qi0WosPn1v0aEOwO8SmeB
      MYSQL_ROOT_PASSWORD: HM62qi0WosPn1v0aEOwO8SmeB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集
    volumes:
      - ../db/__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ../db/deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    networks:
      - tz_open_net

  tz-open-server:
    image: node:20.10-alpine
    container_name: tz-open-next-server
    working_dir: /app
    command: sh -c "npm run build && npm run start:prod"
    volumes:
      - ./:/app
    restart: always
    dns:
      - 172.16.2.110
      - 100.125.1.250
      - 100.125.129.250
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'sso.tzcpa.com:10.16.72.155'
    ports:
      - '2223:6321'
    depends_on:
      - mysql
    networks:
      - tz_open_net

networks:
  tz_open_net:
